---
title: "Fundamentals of Data Analytics and Predictions (FINAL PROJECT)"
date: "4/14/2022"
output: html_document
---

Here will be the following codes for each model we utilized. 

1. Random Forest
```{r}
options(warn=-1) 
library(readr) 
library(caret)
require(mlbench)
library(glmnet)
library(tree)

set.seed(1)
setwd("/Users/davidkim/Desktop/Masters in Public Health/Spring 2022/Fundamentals of Data Analytics and Predictions/project")
train_p = read.csv("project_training set_p.csv", header=TRUE)

set.seed(1)
PD = factor (ifelse(train_p$class == 0, "NonPD", "PD"))
train = data.frame(train_p, PD)

set.seed(1)
ctrl = trainControl(method = "repeatedcv", number=10, savePredictions = "all", classProbs = TRUE)

set.seed(1)
train_RF = train(PD~. -class -id , data = train, method = "rf", preProcess = c("center","scale"), trControl = ctrl)
print(train_RF)

set.seed(1)
varImp(train_RF)

PD_RFTree = tree(PD ~. -class -id, data = train)
summary(PD_RFTree)
```

2. kNN 
```{r}
options(warn=-1) 
library(readr) 
library(caret)
require(mlbench)
library(glmnet)

set.seed(1)
setwd("/Users/davidkim/Desktop/Masters in Public Health/Spring 2022/Fundamentals of Data Analytics and Predictions/project")
train_p = read.csv("project_training set_p.csv", header=TRUE)

set.seed(1)
PD = factor (ifelse(train_p$class == 0, "NonPD", "PD"))
train = data.frame(train_p, PD)

set.seed(1)
train_index <- createDataPartition(train[,"PD"],p=0.75,list=FALSE)
data_trn <- train[train_index,]
data_tst <- train[-train_index,]
ctrl  <- trainControl(method  = "cv",number  = 10) #, summaryFunction = multiClassSummary

knn <- train(PD~. -class -id, data = data_trn, method = "knn",
             trControl = ctrl, 
             preProcess = c("center","scale"), 
             tuneGrid =data.frame(k=seq(5,100, by=5)))

pred <- predict(knn,data_tst)
confusionMatrix(table(data_tst[,"PD"],pred))
print(knn)
plot(knn)
```

3. SVM Linear
```{r}
options(warn=-1) 
library(readr) 
library(caret)
require(mlbench)
library(glmnet)

set.seed(1)
setwd("/Users/davidkim/Desktop/Masters in Public Health/Spring 2022/Fundamentals of Data Analytics and Predictions/project")
train_p = read.csv("project_training set_p.csv", header=TRUE)

set.seed(1)
PD = factor (ifelse(train_p$class == 0, "NonPD", "PD"))
train = data.frame(train_p, PD)

set.seed(1)
ctrl = trainControl(method = "repeatedcv", number=10, savePredictions = "all", classProbs = TRUE)

set.seed(1)
train_SVMLinear = train(PD~. -class -id , data = train, method = "svmLinear", preProcess = c("center","scale"), tuneLength = 20, trControl = ctrl)
print(train_SVMLinear)
```

4. SVM Radial
```{r}
options(warn=-1) 
library(readr) 
library(caret)
require(mlbench)
library(glmnet)

set.seed(1)
setwd("/Users/davidkim/Desktop/Masters in Public Health/Spring 2022/Fundamentals of Data Analytics and Predictions/project")
train = read.csv("project_training set_p.csv", header=TRUE)

set.seed(1)
PD = factor (ifelse(train_p$class == 0, "NonPD", "PD"))
train = data.frame(train, PD)

set.seed(1)
train.index <- createDataPartition(train[,"PD"],p=0.70,list=FALSE)
train1 <- train[train.index,]
test1 <- train[-train.index,]

log_model = glm(PD~. -class -id, data = train1, family = binomial)
summary(log_model)

glm.probs = predict(log_model, test1, type = "response")
summary(glm.probs)

glm.probs = predict(log_model, train1, type = "response")
glm.pred = rep("0", length(glm.probs))
glm.pred[glm.probs > 0.5] = "1"

training_set = train1$PD[1:371]
length(training_set)
length(glm.probs)
table(glm.pred, training_set)

mean(glm.pred == training_set)
```

5. Logistic Regression
```{r}
options(warn=-1) 
library(readr) 
library(caret)
require(mlbench)
library(glmnet)

set.seed(1)
setwd("/Users/davidkim/Desktop/Masters in Public Health/Spring 2022/Fundamentals of Data Analytics and Predictions/project")
train_p = read.csv("project_training set_p.csv", header=TRUE)

set.seed(1)
PD = factor (ifelse(train_p$class == 0, "NonPD", "PD"))
train = data.frame(train_p, PD)

set.seed(1)
ctrl = trainControl(method = "repeatedcv", number=10, savePredictions = "all", classProbs = TRUE)

set.seed(1)
train_Log = train(PD~. -class -id , data = train, method = "glm", preProcess = c("center","scale"), trControl = ctrl)
print(train_Log)
```

6. Naive Bayes
```{r}
options(warn=-1) 
library(readr) 
library(caret)
require(mlbench)
library(glmnet)

set.seed(1)
setwd("/Users/davidkim/Desktop/Masters in Public Health/Spring 2022/Fundamentals of Data Analytics and Predictions/project")
train_p = read.csv("project_training set_p.csv", header=TRUE)

set.seed(1)
PD = factor (ifelse(train_p$class == 0, "NonPD", "PD"))
train = data.frame(train_p, PD)

set.seed(1)
ctrl = trainControl(method = "cv", number=10, savePredictions = "all", classProbs = TRUE)

set.seed(1)
train_NB = train(PD~. -class -id , data = train, method = "nb", metric = "Accuracy", trControl = ctrl)
print(train_NB)
```

7. LDA
```{r}
options(warn=-1) 
library(readr) 
library(caret)
require(mlbench)
library(glmnet)

set.seed(1)
setwd("/Users/davidkim/Desktop/Masters in Public Health/Spring 2022/Fundamentals of Data Analytics and Predictions/project")
train_p = read.csv("project_training set_p.csv", header=TRUE)

set.seed(1)
PD = factor (ifelse(train_p$class == 0, "NonPD", "PD"))
train = data.frame(train_p, PD)

set.seed(1)
ctrl = trainControl(method = "repeatedcv", number=10, savePredictions = "all", classProbs = TRUE)

set.seed(1)
train_LDA = train(PD~. -class -id , data = train, method = "lda", preProcess = c("center","scale"), trControl = ctrl)
print(train_LDA)
```

Prediction using Random Forest
```{r}
#Load library and dataset
options(warn=-1) 
library(readr) 
library(caret)
require(mlbench)
library(glmnet)
library(tree)

setwd("C:/Users/dhkki/Desktop")
train = read.csv("project_training set_p.csv", header=TRUE)
test = read.csv("project_test set_p.csv", header=TRUE)

#factor for column class
set.seed(1)
train$class = as.factor(train$class)
test$class = as.factor(test$class)
levels(train$class)=c("NonPD","PD")
levels(test$class)=c("NonPD","PD")

#training control
ctrl = trainControl(method = "repeatedcv", number=10, savePredictions = "all", classProbs = TRUE,  summaryFunction = twoClassSummary)

#Random Forest on train model
set.seed(1)
train_RF = train(class ~. -id, data = train, method = "rf", preProcess = c("center","scale"), tuneLength = 20, trControl = ctrl)
print(train_RF)

#prediction on test data
test.pred = predict(train_RF, newdata = test)
head(test.pred)

#predicting on test data with previous random forest model on training data
test_data = data.frame(test)
test.data$class = predict(train_RF, newdata = test)

#displaying final test data with the prediction
final_test = test_data[, c("id","class")]
final_test
```
